language: android
sudo: false
android:
  components:
  - build-tools-23.0.1
  - android-23
  
  # Additional components
  - extra-google-m2repository
  - extra-android-m2repository
  - extra-android-support

  # Emulator for the tests
  - sys-img-armeabi-v7a-android-23
addons:
  apt_packages:
    - pandoc
  artifacts:
    paths:
      - $(git ls-files -o | grep app/build/outputs | tr "\n" ":")
after_script:
  # print build failure summary
  - pandoc builder/build/reports/tests/index.html -t plain | sed -n '/^Failed tests/,/default-package/p'
  # print lint results details
  - for f in */app/build/outputs/lint-results.html; do pandoc $f -t plain; done