language: android
sudo: false
jdk: oraclejdk7
env:
  matrix:
    - ANDROID_TARGET=android-23 ANDROID_ABI=armeabi-v7a
  global:
    # wait up to 10 minutes for adb to connect to emulator
    - ADB_INSTALL_TIMEOUT=10

android:
  components:
  - platform-tools
  - tools
  - build-tools-23.0.2
  - android-23

  # Additional components
  - extra-google-m2repository
  - extra-android-m2repository
  - extra-android-support

  # Emulator for the tests
  - sys-img-armeabi-v7a-android-23

cache:
  directories:
    - $HOME/.gradle/caches/2.8
    - $HOME/.gradle/caches/jars-1
    - $HOME/.gradle/daemon
    - $HOME/.gradle/native
    - $HOME/.gradle/wrapper

addons:
  apt_packages:
    - pandoc
  artifacts:
    paths:
      - $(git ls-files -o | grep app/build/outputs | tr "\n" ":")

# Emulator Management: Create, Start and Wait
# From: https://github.com/cotsog/android-tdd-playground/blob/master/.travis.yml
before_script:
  - echo no | android create avd --force --name test --target $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &

# There is an AOSP bug related with API 23, this is the workarround as comented here:
# http://stackoverflow.com/questions/33403743/travis-ci-build-keeps-failing-with-shellcommandunresponsiveexception/33571279#33571279
# If the issue is fixed, you can remove this script section
script:
  - ./gradlew check
  - ./gradlew assembleDebug -PdisablePreDex
  - ./gradlew assembleAndroidTest -PdisablePreDex
  - android-wait-for-emulator
  - adb devices
  - adb shell input keyevent 82 &
  - adb install -r app/build/outputs/apk/app-mock-debug.apk
  - adb install -r app/build/outputs/apk/app-mock-debug-androidTest-unaligned.apk
  # Launches unit tests
  - ./gradlew test --continue
  # Launches androidTests
  - adb shell 'am instrument -w me.panavtec.cleancontacts.mock.test/me.panavtec.cleancontacts.CleanContactsRunner 2>&1 ; exit $?'

after_failure:
  # print lint results details
  - for f in app/build/outputs/lint-results.html; do pandoc $f -t plain; done
  # print build failure summary
  - pandoc builder/build/reports/tests/index.html -t plain | sed -n '/^Failed tests/,/default-package/p'
